name: Generate Table of Content

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-toc:
    name: Generate Table of Content
    runs-on: ubuntu-24.04
    steps:
      - uses: technote-space/toc-generator@v4.3.1